"""empty message

Revision ID: 1fac10840a28
Revises: 97bd417de5ca
Create Date: 2021-04-24 21:28:14.024814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fac10840a28'
down_revision = '97bd417de5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_who_change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_who_change_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_rating_user_id'), 'user_rating', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_rating_user_who_change_id'), 'user_rating', ['user_who_change_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rating_user_who_change_id'), table_name='user_rating')
    op.drop_index(op.f('ix_user_rating_user_id'), table_name='user_rating')
    op.drop_table('user_rating')
    # ### end Alembic commands ###
