"""empty message

Revision ID: 97bd417de5ca
Revises: 
Create Date: 2021-04-24 20:33:59.758029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bd417de5ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.Column('text_color', sa.String(length=6), nullable=True),
    sa.Column('params', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color')
    )
    op.create_index(op.f('ix_categ_name'), 'categ', ['name'], unique=True)
    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_body'), 'change', ['body'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categ_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categ_id'], ['categ.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_categ_id'), 'chain', ['categ_id'], unique=False)
    op.create_index(op.f('ix_chain_user_id'), 'chain', ['user_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_body'), 'comment', ['body'], unique=False)
    op.create_index(op.f('ix_comment_chain_id'), 'comment', ['chain_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('hexagon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selector', sa.String(length=10), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('categ_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('inner_text', sa.String(length=64), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categ_id'], ['categ.id'], ),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hexagon_categ_id'), 'hexagon', ['categ_id'], unique=False)
    op.create_index(op.f('ix_hexagon_chain_id'), 'hexagon', ['chain_id'], unique=False)
    op.create_index(op.f('ix_hexagon_inner_text'), 'hexagon', ['inner_text'], unique=False)
    op.create_index(op.f('ix_hexagon_selector'), 'hexagon', ['selector'], unique=False)
    op.create_index(op.f('ix_hexagon_user_id'), 'hexagon', ['user_id'], unique=False)
    op.create_table('rating_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_change_chain_id'), 'rating_change', ['chain_id'], unique=False)
    op.create_index(op.f('ix_rating_change_user_id'), 'rating_change', ['user_id'], unique=False)
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hex_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hex_id'], ['hexagon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_body'), 'complaint', ['body'], unique=False)
    op.create_index(op.f('ix_complaint_hex_id'), 'complaint', ['hex_id'], unique=False)
    op.create_index(op.f('ix_complaint_user_id'), 'complaint', ['user_id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hex_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['hex_id'], ['hexagon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_hex_id'), 'image', ['hex_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_hex_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_complaint_user_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_hex_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_body'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_index(op.f('ix_rating_change_user_id'), table_name='rating_change')
    op.drop_index(op.f('ix_rating_change_chain_id'), table_name='rating_change')
    op.drop_table('rating_change')
    op.drop_index(op.f('ix_hexagon_user_id'), table_name='hexagon')
    op.drop_index(op.f('ix_hexagon_selector'), table_name='hexagon')
    op.drop_index(op.f('ix_hexagon_inner_text'), table_name='hexagon')
    op.drop_index(op.f('ix_hexagon_chain_id'), table_name='hexagon')
    op.drop_index(op.f('ix_hexagon_categ_id'), table_name='hexagon')
    op.drop_table('hexagon')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_chain_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_body'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_chain_user_id'), table_name='chain')
    op.drop_index(op.f('ix_chain_categ_id'), table_name='chain')
    op.drop_table('chain')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_change_body'), table_name='change')
    op.drop_table('change')
    op.drop_index(op.f('ix_categ_name'), table_name='categ')
    op.drop_table('categ')
    # ### end Alembic commands ###
