"""empty message

Revision ID: abe0b62b0bb0
Revises: af926c95719c
Create Date: 2021-04-01 14:51:35.833471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe0b62b0bb0'
down_revision = 'af926c95719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaint_body', table_name='complaint')
    op.create_index(op.f('ix_complaint_body'), 'complaint', ['body'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_body'), table_name='complaint')
    op.create_index('ix_complaint_body', 'complaint', ['body'], unique=1)
    # ### end Alembic commands ###
