"""empty message

Revision ID: af926c95719c
Revises: 29b52c52d4b3
Create Date: 2021-04-01 12:56:53.230867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af926c95719c'
down_revision = '29b52c52d4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hex_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hex_id'], ['hexagon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_body'), 'complaint', ['body'], unique=True)
    op.create_index(op.f('ix_complaint_hex_id'), 'complaint', ['hex_id'], unique=False)
    op.create_index(op.f('ix_complaint_user_id'), 'complaint', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_user_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_hex_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_body'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
