"""empty message

Revision ID: bb7bf1fec634
Revises: 1fac10840a28
Create Date: 2021-04-26 19:15:33.628357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7bf1fec634'
down_revision = '1fac10840a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('ext', sa.String(length=5), nullable=True))
    op.drop_column('image', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('filename', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('image', 'ext')
    # ### end Alembic commands ###
