"""empty message

Revision ID: dae9b5f8e176
Revises: 0438211b7eb4
Create Date: 2021-04-17 22:24:09.089691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae9b5f8e176'
down_revision = '0438211b7eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_change_chain_id'), 'rating_change', ['chain_id'], unique=False)
    op.create_index(op.f('ix_rating_change_user_id'), 'rating_change', ['user_id'], unique=False)
    op.drop_column('comment', 'rating_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rating_change', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_rating_change_user_id'), table_name='rating_change')
    op.drop_index(op.f('ix_rating_change_chain_id'), table_name='rating_change')
    op.drop_table('rating_change')
    # ### end Alembic commands ###
