"""empty message

Revision ID: e28a21f70e13
Revises: b8de5f08a778
Create Date: 2021-03-28 21:29:30.869002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28a21f70e13'
down_revision = 'b8de5f08a778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hexagon', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hexagon', 'created_at')
    # ### end Alembic commands ###
